services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo:local
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_PROMPT: ${GEMINI_PROMPT}
      JWT_SECRET: ${JWT_SECRET}
