services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo:local
    ports:
      - "8090:8090"
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_PROMPT: ${GEMINI_PROMPT}


    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-bookworm
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: "Asia/Seoul"
      PGTZ: "Asia/Seoul"
    volumes:
      - ./database/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER || exit 1",
        ]

