spring:
  application:
    name: tikitaka
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
server:
  port: 8090

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-3.5-flash
  prompt: ${GEMINI_PROMPT}

